[package]
authors = ["Aaronepower <theaaronepower@gmail.com>"]
build = "build.rs"
description = "A utility that allows you to count code, quickly."
homepage = "https://tokei.rs"
include = ["src/**/*", "languages.json", "build.rs", "cli.yml", "Cargo.toml", "LICENCE-APACHE", "LICENCE-MIT"]
license = "MIT/Apache-2.0"
name = "tokei"
readme = "README.md"
repository = "https://github.com/Aaronepower/tokei.git"
version = "5.0.1"

[profile.release]
debug = true
panic="abort"

[build-dependencies]
serde = "0.8"
serde_json = "0.8"
errln = "0.1"

[build-dependencies.handlebars]
features = ["serde_type"]
version = "~0.24"

[build-dependencies.serde_codegen]
optional = true
version = "0.8"

[dependencies]
encoding = "0.2"
errln = "0.1"
ignore = "0.1"
lazy_static = "0.2"
log = "0.3"
maplit = "0.1"
rayon = "0.6"
regex = "0.1"

[dependencies.clap]
features = ["yaml"]
version = "2.19"

[dependencies.env_logger]
features = []
version = "0.3"

[dependencies.hex]
version = "0.2"
optional = true

[dependencies.serde]
optional = true
version = "0.8"

[dependencies.serde_cbor]
optional = true
version = "0.4"

[dependencies.serde_json]
optional = true
version = "0.8"

[dependencies.serde_yaml]
optional = true
version = "0.4"

[dependencies.toml]
default-features = false
features = ["serde"]
optional = true
version = "0.2"

[dev-dependencies]
tempdir = "0.3"

[features]
all = ["json", "cbor", "toml-io", "yaml"]
cbor = ["io", "hex", "serde_cbor"]
default = []
io = ["serde_codegen", "serde"]
json = ["io", "serde_json"]
toml-io = ["io", "toml/serde"]
yaml = ["io", "serde_yaml"]
