[package]
authors = ["Erin Power <xampprocky@gmail.com>"]
build = "build.rs"
categories = ["command-line-utilities", "development-tools", "visualization"]
description = "Count your code, quickly."
edition = "2018"
homepage = "https://tokei.rs"
include = ["Cargo.lock", "Cargo.toml", "LICENCE-APACHE", "LICENCE-MIT", "build.rs", "languages.json", "src/**/*"]
keywords = ["utility", "cli", "cloc", "lines", "statistics"]
license = "MIT/Apache-2.0"
name = "tokei"
readme = "README.md"
repository = "https://github.com/XAMPPRocky/tokei.git"
version = "11.0.0"

[features]
all = ["json", "cbor", "yaml"]
cbor = ["hex", "serde_cbor"]
default = []
json = ["serde_json"]
yaml = ["serde_yaml"]

[profile.release]
lto = "thin"
panic = "abort"

[badges.appveyor]
repository = "XAMPPRocky/tokei"
[badges.travis-ci]
repository = "XAMPPRocky/tokei"

[build-dependencies]
handlebars = "3.0.1"
ignore = "0.4.14"
lazy_static = "1.4.0"
serde_json = "1.0.51"

[dependencies]
aho-corasick = "0.7.10"
clap = "2.33.0"
crossbeam-channel = "0.4.2"
dirs = "2.0.2"
encoding_rs_io = "0.1.7"
grep-searcher = "0.1.7"
ignore = "0.4.14"
log = "0.4.6"
rayon = "1.3.0"
serde = { version = "1.0.106", features = ["derive", "rc"] }
term_size = "0.3.1"
toml = "0.5.6"
parking_lot = "0.10.0"
dashmap = { version = "3.11.0", features = ["serde"] }
lazy_static = "1.4.0"

[dependencies.env_logger]
features = []
version = "0.7.1"

[dependencies.hex]
optional = true
version = "0.4.2"

[dependencies.serde_cbor]
optional = true
version = "0.11.1"

[dependencies.serde_json]
optional = true
version = "1.0.51"

[dependencies.serde_yaml]
optional = true
version = "0.8.11"

[dev-dependencies]
lazy_static = "1.4.0"
regex = "1.3.6"
tempfile = "3.0.8"
git2 = { version = "0.13.0", default-features = false, features = [] }
