[package]
authors = ["Erin Power <xampprocky@gmail.com>"]
build = "build.rs"
categories = ["command-line-utilities", "development-tools", "visualization"]
description = "Count your code, quickly."
edition = "2018"
homepage = "https://tokei.rs"
include = ["Cargo.lock", "Cargo.toml", "LICENCE-APACHE", "LICENCE-MIT", "build.rs", "languages.json", "src/**/*"]
keywords = ["utility", "cli", "cloc", "lines", "statistics"]
license = "MIT/Apache-2.0"
name = "tokei"
readme = "README.md"
repository = "https://github.com/XAMPPRocky/tokei.git"
version = "12.1.1"

[features]
all = ["cbor", "yaml"]
cbor = ["hex", "serde_cbor"]
default = []
yaml = ["serde_yaml"]

[profile.release]
lto = "thin"
panic = "abort"

[build-dependencies]
tera = "1.6.1"
ignore = "0.4.17"
serde_json = "1.0.61"

[dependencies]
aho-corasick = "0.7.15"
clap = "2.33.3"
crossbeam-channel = "0.5.0"
dirs = "3.0.1"
encoding_rs_io = "0.1.7"
grep-searcher = "0.1.7"
ignore = "0.4.17"
log = "0.4.11"
rayon = "1.5.0"
serde = { version = "1.0.118", features = ["derive", "rc"] }
term_size = "0.3.2"
toml = "0.5.8"
parking_lot = "0.11.1"
dashmap = { version = "4.0.1", features = ["serde"] }
num-format = "0.4.0"
once_cell = "1.5.2"
regex = "1.4.3"
serde_json = "1.0.61"

[dependencies.env_logger]
features = []
version = "0.8.2"

[dependencies.hex]
optional = true
version = "0.4.2"

[dependencies.serde_cbor]
optional = true
version = "0.11.1"

[dependencies.serde_yaml]
optional = true
version = "0.8.15"

[dev-dependencies]
regex = "1.4.3"
tempfile = "3.0.8"
git2 = { version = "0.13.15", default-features = false, features = [] }
