[package]
authors = ["Erin Power <xampprocky@gmail.com>"]
build = "build.rs"
categories = ["command-line-utilities", "development-tools", "visualization"]
description = "A utility that allows you to count code, quickly."
edition = "2018"
homepage = "https://tokei.rs"
include = ["Cargo.lock", "Cargo.toml", "LICENCE-APACHE", "LICENCE-MIT", "build.rs", "languages.json", "src/**/*"]
keywords = ["utility", "cli", "cloc", "lines", "statistics"]
license = "MIT/Apache-2.0"
name = "tokei"
readme = "README.md"
repository = "https://github.com/XAMPPRocky/tokei.git"
version = "10.0.1"

[badges]
[badges.appveyor]
repository = "XAMPPRocky/tokei"

[badges.travis-ci]
repository = "XAMPPRocky/tokei"

[build-dependencies]
handlebars = "2.0.2"
ignore = "0.4.7"
lazy_static = "1.4.0"
serde_json = "1.0.41"

[dependencies]
clap = "2.33.0"
dirs = "2.0.2"
encoding_rs_io = "0.1.6"
ignore = "0.4.7"
log = "0.4.6"
rayon = "1.2.0"
serde = "1.0.92"
serde_derive = "1.0.101"
term_size = "0.3.1"
toml = "0.5.3"
grep-searcher = "0.1.6"

[dependencies.env_logger]
features = []
version = "0.7.0"

[dependencies.hex]
optional = true
version = "0.3.2"

[dependencies.serde_cbor]
optional = true
version = "0.10.2"

[dependencies.serde_json]
optional = true
version = "1.0.41"

[dependencies.serde_yaml]
optional = true
version = "0.8.11"

[dev-dependencies]
lazy_static = "1.4.0"
regex = "1.2.0"
tempfile = "3.0.8"
git2 = { version = "0.10.1", default-features = false, features = [] }

[features]
all = ["json", "cbor", "yaml"]
cbor = ["hex", "serde_cbor"]
default = []
json = ["serde_json"]
yaml = ["serde_yaml"]

[profile]
[profile.release]
lto = true
panic = "abort"
