[package]
authors = ["Erin Power <xampprocky@gmail.com>"]
build = "build.rs"
categories = ["command-line-utilities", "development-tools", "visualization"]
description = "Count your code, quickly."
edition = "2018"
homepage = "https://tokei.rs"
include = ["Cargo.lock", "Cargo.toml", "LICENCE-APACHE", "LICENCE-MIT", "build.rs", "languages.json", "src/**/*"]
keywords = ["utility", "cli", "cloc", "lines", "statistics"]
license = "MIT/Apache-2.0"
name = "tokei"
readme = "README.md"
repository = "https://github.com/XAMPPRocky/tokei.git"
version = "12.0.4"

[features]
all = ["cbor", "yaml"]
cbor = ["hex", "serde_cbor"]
default = []
yaml = ["serde_yaml"]

[profile.release]
lto = "thin"
panic = "abort"

[build-dependencies]
tera = "1.5.0"
ignore = "0.4.16"
serde_json = "1.0.57"

[dependencies]
aho-corasick = "0.7.13"
clap = "2.33.2"
crossbeam-channel = "0.4.2"
dirs = "2.0.2"
encoding_rs_io = "0.1.7"
grep-searcher = "0.1.7"
ignore = "0.4.16"
log = "0.4.6"
rayon = "1.3.1"
serde = { version = "1.0.115", features = ["derive", "rc"] }
term_size = "0.3.2"
toml = "0.5.6"
parking_lot = "0.11.0"
dashmap = { version = "3.11.10", features = ["serde"] }
num-format = "0.4.0"
once_cell = "1.4.0"
regex = "1.3.9"
serde_json = "1.0.57"

[dependencies.env_logger]
features = []
version = "0.7.1"

[dependencies.hex]
optional = true
version = "0.4.2"

[dependencies.serde_cbor]
optional = true
version = "0.11.1"

[dependencies.serde_yaml]
optional = true
version = "0.8.12"

[dev-dependencies]
regex = "1.3.9"
tempfile = "3.0.8"
git2 = { version = "0.13.5", default-features = false, features = [] }
