[package]
authors = ["Aaronepower <theaaronepower@gmail.com>"]
build = "build.rs"
description = "A utility that allows you to count code, quickly."
homepage = "https://tokei.rs"
include = [
    "Cargo.lock",
    "Cargo.toml",
    "LICENCE-APACHE",
    "LICENCE-MIT",
    "build.rs",
    "languages.json",
    "src/**/*"
]
license = "MIT/Apache-2.0"
name = "tokei"
readme = "README.md"
repository = "https://github.com/Aaronepower/tokei.git"
version = "6.1.3"
keywords = ["utility", "cli", "cloc", "lines", "statistics"]
categories = ["command-line-utilities", "development-tools", "visualization"]

[badges]
travis-ci = { repository = "Aaronepower/tokei" }
appveyor = { repository = "Aaronepower/tokei" }

[profile.release]
panic="abort"
lto=true

[build-dependencies]
serde_json = "1"
ignore = "0.3"
handlebars = "0.29"
lazy_static = "1"

[dependencies]
encoding = "0.2"
ignore = "0.3"
log = "0.4"
rayon = "0.9"
regex = "0.2"
clap = "2.24"

[dependencies.env_logger]
features = []
version = "0.5.0-rc.2"

[dependencies.hex]
version = "0.3"
optional = true

[dependencies.serde]
optional = true
version = "1"

[dependencies.serde_derive]
optional = true
version = "1"

[dependencies.serde_cbor]
optional = true
version = "0.8"

[dependencies.serde_json]
optional = true
version = "1"

[dependencies.serde_yaml]
optional = true
version = "0.7"

[dependencies.toml]
optional = true
version = "0.4"

[dev-dependencies]
tempdir = "0.3"
lazy_static = "1"

[features]
all = ["json", "cbor", "toml-io", "yaml"]
cbor = ["io", "hex", "serde_cbor"]
default = []
io = ["serde_derive", "serde"]
json = ["io", "serde_json"]
toml-io = ["io", "toml"]
yaml = ["io", "serde_yaml"]
