[package]
authors = ["Aaronepower <theaaronepower@gmail.com>"]
build = "build.rs"
categories = ["command-line-utilities", "development-tools", "visualization"]
description = "A utility that allows you to count code, quickly."
homepage = "https://tokei.rs"
include = ["Cargo.lock", "Cargo.toml", "LICENCE-APACHE", "LICENCE-MIT", "build.rs", "languages.json", "src/**/*"]
keywords = ["utility", "cli", "cloc", "lines", "statistics"]
license = "MIT/Apache-2.0"
name = "tokei"
readme = "README.md"
repository = "https://github.com/Aaronepower/tokei.git"
version = "8.0.1"

[badges]
[badges.appveyor]
repository = "Aaronepower/tokei"

[badges.travis-ci]
repository = "Aaronepower/tokei"

[build-dependencies]
handlebars = "1"
ignore = "0.4"
lazy_static = "1"
serde_json = "1"

[dependencies]
clap = "2"
dirs = "1"
encoding_rs_io = "0.1"
ignore = "0.4"
log = "0.4"
rayon = "1"
serde = "1"
serde_derive = "1"
term_size = "0.3.1"
toml = "0.4.10"

[dependencies.env_logger]
features = []
version = "0.5.0"

[dependencies.hex]
optional = true
version = "0.3"

[dependencies.serde_cbor]
optional = true
version = "0.9"

[dependencies.serde_json]
optional = true
version = "1"

[dependencies.serde_yaml]
optional = true
version = "0.8"

[dev-dependencies]
lazy_static = "1"
regex = "1.0"
tempdir = "0.3"

[features]
all = ["json", "cbor", "yaml"]
cbor = ["hex", "serde_cbor"]
default = []
json = ["serde_json"]
yaml = ["serde_yaml"]

[profile.release]
lto = true
panic = "abort"
